synt += ../Top.v
synt += ../Controller.v
synt += ../Keyboard.v
synt += ../../generic/Serial.v
synt += ../../generic/Shiftreg.v
synt += ../../generic/Counter.v
synt += ../../generic/Edge_Detector.v
synt += ../../generic/Bits_Reverse.v

sim += $(synt)
sim += ../sim/TopTest.v
sim += ../sim/TopTestBench.v
sim += ../sim/Keyboard_behav.v
sim += ../../generic/sim/Clock.v
sim += ../../generic/sim/Reset.v
sim += ../../generic/sim/Monitor.v
sim += ../../generic/sim/Set.v

include ../../generic/makefile/generic
