synt += ../mouse.v
synt += ../Top.v
synt += ../ps2_rxtx.v
synt += ../ps2_rx.v
synt += ../ps2_tx.v
synt += ../PS2.v
synt += ../PS2_Reader.v
synt += ../PS2_Writer.v
synt += ../../generic/Serial.v
synt += ../../generic/Shiftreg.v
synt += ../../generic/Counter.v

sim += $(synt)
sim += ../sim/TopTest.v
sim += ../sim/MouseTestBench.v
sim += ../../generic/sim/ps2/PS2_behav.v
sim += ../../generic/sim/ps2/Mouse_behav.v
sim += ../../generic/sim/Clock.v
sim += ../../generic/sim/Reset.v
sim += ../../generic/sim/Monitor.v
sim += ../../generic/sim/Set.v

include ../../generic/makefile/generic
