synt += ../Top.v
synt += ../serialfun.v
synt += ../Rs232Tx.v
synt += ../Rs232Rx.v
synt += ../../generic/BaudRateGenerator.v
synt += ../../generic/Serial.v
synt += ../../generic/Counter.v
synt += ../../generic/Shiftreg.v

sim += $(synt)
sim += ../TopTest.v
sim += ../Rs232-behav.v
sim += ../../generic/sim/Clock.v
sim += ../../generic/sim/Reset.v

include ../../generic/makefile/generic
