synt += ../Top.v
synt += ../Controller.v
synt += ../Sync.v
synt += ../../generic/Counter.v

sim += $(synt)
sim += ../sim/TopTest.v
sim += ../sim/TopTestBench.v
sim += ../../generic/sim/Clock.v
sim += ../../generic/sim/Reset.v

include ../../generic/makefile/generic
