synt += ../Top.v
synt += ../Controller.v
synt += ../Mouse_PS2.v
synt += ../PS2.v
synt += ../PS2_Reader.v
synt += ../PS2_Writer.v
synt += ../Edge_Detector.v
synt += ../../generic/Serial.v
synt += ../../generic/Shiftreg.v
synt += ../../generic/Counter.v

sim += $(synt)
sim += ../sim/TopTest.v
sim += ../sim/MouseTestBench.v
sim += ../../generic/sim/ps2/PS2_behav.v
sim += ../../generic/sim/ps2/Mouse_behav.v
sim += ../../generic/sim/Clock.v
sim += ../../generic/sim/Reset.v
sim += ../../generic/sim/Monitor.v
sim += ../../generic/sim/Set.v

include ../../generic/makefile/generic
