synt += ../Top.v
synt += ../Rs232Echo.v
synt += ../Rs232Tx.v
synt += ../Rs232Rx.v
synt += ../../generic/BaudRateGenerator.v
synt += ../../generic/Serial.v
synt += ../../generic/Counter.v
synt += ../../generic/Shiftreg.v

sim += $(synt)
sim += ../sim/TopTest.v
sim += ../sim/Rs232.v
sim += ../sim/Rs232_behav.v
sim += ../../generic/sim/Clock.v
sim += ../../generic/sim/Reset.v
sim += ../../generic/sim/Monitor.v
sim += ../../generic/sim/Set.v

include ../../generic/makefile/generic
