synt += ../Top.v
synt += ../Controller.v
synt += ../Rotor.v
synt += ../../generic/Counter.v
synt += ../../generic/Debouncer.v
sim += ../../generic/sim/Set.v

sim += $(synt)
sim += ../sim/TopTest.v
sim += ../sim/TopTestBench.v
sim += ../sim/Rotor_behav.v
sim += ../../generic/sim/Clock.v
sim += ../../generic/sim/Reset.v

include ../../generic/makefile/generic
