synt += ../Top.v
synt += ../Controller.v
synt += ../Sync.v
synt += ../../generic/Counter.v

sim += $(synt)
sim += ../sim/TopTest.v
sim += ../sim/TopTestBench.v
sim += ../sim/Vga_Behav.v
sim += ../sim/Vga_Behav_Lines_Counter.v
sim += ../sim/Vga_Behav_Sync.v
sim += ../../generic/sim/Clock.v
sim += ../../generic/sim/Reset.v
sim += ../../generic/sim/Monitor.v
sim += ../../generic/sim/Logs.v

include ../../generic/makefile/generic
